### ISSUE TITLE
Release 1.1.13 on npmjs?

### ISSUE THREAD

**Issue by yeeland** [johannesjo/angular-promise-buttons#10]
Hi, I noticed that https://www.npmjs.com/package/angular-promise-buttons is still at 1.1.11 for the latest version but bower is at 1.1.13. Would it be possible for you to do a release to npm as well? Thanks!

**Comment by johannesjo** [comment]
I probably should automate this as well. Thanks for reminding me. The new version is published.

**Comment by yeeland** [comment]
No problem. Thanks for getting it out this quickly!
