### ISSUE TITLE
Problem in using it in ng-repeat

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/angular-promise-buttons#2]
If i use it in ng-repeat, all buttons in ng-repeat, shows busy indicator

**Comment by johannesjo** [comment]
Thanks for reporting. Could you by any chance provide a plunkr with this issue ( you could fork the demo-plunkr for that, if you like)?

**Comment by tushariscoolster** [comment]
http://plnkr.co/edit/7vfXgVrWef3ptpcQKpqA?p=preview

**Comment by johannesjo** [comment]
That's the expected behaviour. All buttons share the same promise, so they're all triggered when the promise is in the pending state.

**Comment by tushariscoolster** [comment]
Yups , i know, it hold same promise, but do you think it make any sense to show busy button for all?

**Comment by johannesjo** [comment]
Yes I think so. Maybe not necesserialy the loading indicator, but imho you
most likely would want to deactivate all buttons for the same promise when
it is pending, don't you think?

Tushar Borole <notifications@github.com> schrieb am Do., 11. Juni 2015
04:50:

**Comment by tushariscoolster** [comment]
Yups that will perfectly make sense?
I dont think with current cofiguration of plugin, you can do that

**Comment by johannesjo** [comment]
No you can't . Actually I like the simplicity of the module, but if you need this feature you could of course provide a pull request :)

**Comment by johannesjo** [comment]
I'all added an option to do so with the latest version :)

**Comment by tushariscoolster** [comment]
@johannesjo  tnx :)
