### ISSUE TITLE
Custom form attribute name (instead of ngSubmit)

### ISSUE THREAD

**Issue by portus84** [johannesjo/angular-promise-buttons#21]
Hi,
I have a custom directive to validate form before submit (validSubmit instead of ngSubmit), it's possible to customize SUBMIT_ATTR to include arbitrary attribute name?

Thank's so much.

**Comment by johannesjo** [comment]
Ng-fab-form listens to the forms submit event, so as far as I can see (haven't looked at the source yet), the attribute name should not matter, as long as the forms submit event is triggered.

**Comment by johannesjo** [comment]
Oh. Sorry! Wrong repo. Ähem. No currently there is no way to customize the submit attribute, but the functionality should be easy to implement actually. Not sure when I will find time for this, but managing feel free to submit a PR.
