### ISSUE TITLE
[Enhancement] Add the possibility of defining CLICK_ATTR as parameter

### ISSUE THREAD

**Issue by Totemika** [johannesjo/angular-promise-buttons#27]
Being ngClick the default CLICK_ATTR but being able to use another directive instead.

I have a custom directive for clicking and doing this really helps.

**Comment by johannesjo** [comment]
I made the attributes configurable. Maybe you can check it out and tell me if it works for you.

**Comment by Totemika** [comment]
Thank you very much, @johannesjo !! Now I can use it without modifying your directive.
