### ISSUE TITLE
Angular-material bug: The spinner does not show up

### ISSUE THREAD

**Issue by SamarRizvi** [johannesjo/angular-promise-buttons#28]
The spinner does not show up in case of a promise but the button is disabled. On further inspection, I found out that the spinner template doesn't get added at all.

**Comment by mrbatista** [comment]
@SamarRizvi it is necessari to configure prority directive into provider

**Comment by SamarRizvi** [comment]
I did not understand @mrbatista . An example, may be.

**Comment by SamarRizvi** [comment]
@mrbatista Why do I not see your `$compile` changes in the recent release, nor in the current master.

**Comment by mrbatista** [comment]
@SamarRizvi sorry for the short response.
md-button directive has translude options enabled see [source code](https://github.com/angular/material/blob/master/src/components/button/button.js#L122).
It is necessary to modify priority of `angular-promise-buttons` directive to `md-button` and `angular-promise-buttons` directives works together.
See example belove:
```javascript
  angularPromiseButtonsProvider.extendConfig({
    spinnerTpl: 'customHtmlTemplate',
    priority: 1
  });
```

**Comment by mrbatista** [comment]
@johannesjo [this commit](https://github.com/johannesjo/angular-promise-buttons/commit/06885453ec31d47bbb596e50cabbb2c48033051c) remove my enhancement introduced by PR -> https://github.com/johannesjo/angular-promise-buttons/pull/23
Is there a particular reason?

**Comment by mrbatista** [comment]
Is necessary to add unit test to coverage this case...

**Comment by johannesjo** [comment]
@mrbatista I'm not sure to be honest. This looks like something got mixed up during the automatic merge. There are also some other things lost, which should be there (e.g. the configurable click and submit events and attributes)..

@SamarRizvi You should be able to use 0.1.16 until this is resolved.

I'll try to find time, to dig into it this Friday. I can't promise anything though.

**Comment by mrbatista** [comment]
@SamarRizvi for the moment install version 0.1.16 until @johannesjo fix regression introduced by other PR.

**Comment by johannesjo** [comment]
@SamarRizvi I'll reintroduced the changes made by @mrbatista  in the commit 4ce8b4c35f22d1c9a829a8459c3414797ddb20bf. You should be able to use version 0.1.18 as described by @mrbatista:
```
 angularPromiseButtonsProvider.extendConfig({
    spinnerTpl: 'customHtmlTemplate',
    priority: 1
  });
```
