### ISSUE TITLE
Spinner not showing

### ISSUE THREAD

**Issue by charliebrink** [johannesjo/angular-promise-buttons#3]
I'm trying to implement your component but I'm not getting the spinner to show during progress. The disabling of the button works fine. Any ideas on what I;m missing or what I should look for?

**Comment by johannesjo** [comment]
Did you include some css for the spinners? It's not included per default.

**Comment by charliebrink** [comment]
Yeah, i added this:

.btn-spinner:not(:required) {
  margin-left: -22px;
  opacity: 0;
  transition: 0.4s margin ease-out, 0.2s opacity ease-out; }

.is-loading .btn-spinner {
  transition: 0.2s margin ease-in, 0.4s opacity ease-in;
  margin-left: 5px;
  opacity: 1; }

.btn {
  text-align: left; }

**Comment by johannesjo** [comment]
Try including all of this: https://github.com/johannesjo/angular-promise-buttons/blob/master/src/styles/_default-button.scss

Seems to be an styling issue to me.

**Comment by charliebrink** [comment]
Got it sorted, thanks; It was a styling issue.
