### ISSUE TITLE
promise-btn and angular confirm

### ISSUE THREAD

**Issue by twilly86** [johannesjo/angular-promise-buttons#31]
I am trying to add two directives to a button, one is promise-btn, then other is angular-confirm, which pops open a bootstrap dialog asking if they are sure they want to delete something.

I'm getting the following error...

`Multiple directives [confirm, promiseBtn] asking for new/isolated scope on: <button class="btn btn-danger" ng-click="Undo(item)" ng-if="item.Result == 'UnTested'" promise-btn="" confirm="Are you sure?"`

Any ideas on how to get both working?

**Comment by johannesjo** [comment]
I'm afraid that there is probably no easy way to do this, as you can't have multiple directives with an isolate scope on the same element. Also both directives are manipulating the DOM so there might be possible conflicts. 

See: http://stackoverflow.com/questions/22303368/multiple-directives-mypopup-mydraggable-asking-for-new-isolated-scope

**Comment by twilly86** [comment]
i saw you can move promise-btn to the form, would this work? and have the confirm directive on the button?

**Comment by johannesjo** [comment]
If you have a form this might work (though there might be problems due to the dom manipulation going on).

**Comment by twilly86** [comment]
k, thanks for the info, closing

**Comment by johannesjo** [comment]
Tell me, if you found a solution.
