### ISSUE TITLE
Bug: plugin breaks angular-ui bootstrap tooltips

### ISSUE THREAD

**Issue by MaxKorz** [johannesjo/angular-promise-buttons#32]
Hi. Thanks for your plugin. It's really great! I found a bug.

Demo: http://plnkr.co/edit/ImxzzVoS29QYD46OtMQ7?p=preview
Hover over the button to see the tooltip
Hover out to see that the tooltip disappears

Then hover over the button again and click on it. You will see the angular-promise-buttons spinner. But when you hover out the tooltip won't disappear.

**Comment by MaxKorz** [comment]
Ooops. I found the cause. The [disabled] state has a "pointer-events: none" rule, that's why the angular-ui bootstrap can't detect the mouseleave event.

**Comment by johannesjo** [comment]
Glad you found the reason :)
