### ISSUE TITLE
angular-promise-buttons and angular 2

### ISSUE THREAD

**Issue by Darkein** [johannesjo/angular-promise-buttons#35]
Hello, i'm a user of angular-promise-buttons and i just love it. Now i'm using Angular 2 and i wonder if you plan to upgrade your component to work with it?

Thanks for your great job!

**Comment by johannesjo** [comment]
Hello! I'm glad that you like the component. There are definitely plans to update the component though currently I don't have too much free time on my hands so I can't really say when it will happen. I'll keep you updated!

**Comment by Darkein** [comment]
I'm glad to hear that, thanks!

**Comment by johannesjo** [comment]
I finally found the time to work on that. Hopefully I will be done by the end of the next week. You can find the repository here: https://github.com/johannesjo/angular2-promise-buttons

**Comment by johannesjo** [comment]
Should be done now.
