### ISSUE TITLE
support for Font-Awesome

### ISSUE THREAD

**Issue by IbrahimHd** [johannesjo/angular-promise-buttons#37]
Hi,
As I'm already using font awesome for icons (and I think the majority are as well), I'm think to **make use of the already built css style** for my `promise-buttons`.  I tried to configure the template as the following:
```
.config(function (angularPromiseButtonsProvider)
        {
            angularPromiseButtonsProvider.extendConfig({
                spinnerTpl: '<i class="fa fa-spinner fa-pulse"></i>'
            });
        });
```
The issue is that the icon keeps displayed and spin initially.
I expect the template is going to be shown only when the promise is fired/starts (but not initially and before the promise is run).
Dose it make sense? Is something missing?

**Comment by johannesjo** [comment]
Hey there! Thanks for posting. If you post a plunkr I can have a look at it, but I don't think that this is really related to angular-promise-buttons as it is just an css issue.

**Comment by IbrahimHd** [comment]
Hi!
Please refer to this [plunkr](http://plnkr.co/edit/2gkhqbKK1zmr8DBwrIUs?p=preview) for better understanding.

**Comment by johannesjo** [comment]
You have to set the icon to not display via css and then display it by targeting it via .is-loading parent selector.

**Comment by IbrahimHd** [comment]
I know that but I mean if this can be controlled inside the directive.
Straightforward, can the directive display `spinnerTpl` only when the promise is fired?
(something like: `ng-if="isLoading"`)

**Comment by johannesjo** [comment]
No.
