### ISSUE TITLE
using promise-btn with [input] element and ng-change

### ISSUE THREAD

**Issue by IbrahimHd** [johannesjo/angular-promise-buttons#38]
Hi,

I have an `input` element for searching data and the promise is fired with `ng-change` like this:
`<input type="text" ng-model="searchItemsInput" ng-change="searchItems(searchItemsInput)" promise-btn>`

Is there away that I can make it works with an (input with ng-change)?
Thanks in advance.

**Comment by johannesjo** [comment]
You could try changing the click event listener to [input](https://developer.mozilla.org/de/docs/Web/Events/input):
```
    CLICK_EVENT: 'input',
    CLICK_ATTR: 'ngChange',
```

**Comment by IbrahimHd** [comment]
Thank you for your answer.
Actually I couldn't tackle it correctly. Could you please have a look on this 
[plunkr](http://plnkr.co/edit/fMkNDksMPnSTNc5f7ohb?p=preview) and advice accordingly

**Comment by johannesjo** [comment]
This needs to be changed in the config phase via a config function as it is not possible to change the event handlers at runtime.

**Comment by johannesjo** [comment]
http://plnkr.co/edit/i7lHig4NlKtiPAEa7UdN?p=preview

**Comment by IbrahimHd** [comment]
Actually I have tried to change it in the config phase before putting in the attribute not nothing showed up.
I can't see the indicator in the plunkr you sent. Does it work at your side?
(if not, do I need to do an extra CSS stuff?)

**Comment by johannesjo** [comment]
Thinking about it. It probably won't work because you can't append html to inputs and you also can't  use pseudo classes with them: http://plnkr.co/edit/i7lHig4NlKtiPAEa7UdN?p=preview

So no promise btns doesn't work with inputs.

**Comment by IbrahimHd** [comment]
I think you are very close to the solution!
Could the input be wrapped in <div> like this
```
    <div class="searchBox">
      <input type="text" ng-model="searchItemsInput" ng-change="myPromise()" promise-btn/>
      <span class="fa fa-spinner fa-pulse input-spinner"></span>
    </div>
```
Here I'm relying on the `is-loading` class.
You can find this working example:
http://plnkr.co/edit/i7lHig4NlKtiPAEa7UdN?p=preview

For me I'm satisfied with this approach but I'm sharing this in case you see it can be done as a built-in feature.
Thnx

**Comment by johannesjo** [comment]
For wrapping support this directive would need a major rewrite. As it's called angular-promise-**buttons** I don't see this happening any time soon :)

But maybe this is helpful to you: https://github.com/cgross/angular-busy

**Comment by IbrahimHd** [comment]
Maybe it makes more sense to be as a different directive, angular-promise-**input** :-)
Anyway, thanks a lot for your effort!
