### ISSUE TITLE
promise-btn overrides original $event

### ISSUE THREAD

**Issue by maxkorz** [johannesjo/angular-promise-buttons#39]
Hi there! I'm having an issue with your plugin.
I'm using nested ng-click like this:
```
<div ng-repeat="item in $ctrl.notifications">
  <div ng-click="$ctrl.openNotification(item)">
    <button type="button" ng-click="$ctrl.markAsRead(item)" promise-btn>Mark as read</button>
  </div> 
</div>
```

As you can see, I have a list of notifications. You can open a notification by clicking on a div. And you can mark it as read by clicking on a button inside div.

But I don't want to open notification when I mark it as read, so I do $event.stopPropagation() to prevent the event from bubbling up the DOM tree. But I can't do this because promise-btn directive overrides original $event and instead of MouseEvent I get a string "click".

I hope you can help me.

**Comment by johannesjo** [comment]
Hi! Thanks for posting. You should be able to work around this by passing the promise to the directive directly. See #11

**Comment by maxkorz** [comment]
Hi. Thanks a lot for the link. I ended up using this approach:
```
<div ng-click="$ctrl.openNotification(item)">
    <div ng-click="$event.preventDefault()">
        <button type="button" ng-click="$ctrl.markAsRead(item)" promise-btn>Mark as read</button>
    </div>
</div>
```

I think you should mention this bug in Readme. I spent a lot of time trying to figure out the cause of the problem. There's nothing similar in google so I began to simplify my code until I came across the source of the problem. A simple mention in the Readme would be very useful. Problem is kinda solved, you can close this issue.

**Comment by johannesjo** [comment]
This looks complicated.  Why wouldn't you use this approach:
```
<button ng-click="click()" promise-btn="clickPromise">Clickclick</button>
```
```
$scope.click= function(){
   $scope.clickPromise = asyncServiceCaller...
}
```
