### ISSUE TITLE
How do we stop the animation on form succes?

### ISSUE THREAD

**Issue by isbara** [johannesjo/angular-promise-buttons#4]
Thank you for your great work. Its awesome. Maybe this not a issue but I am stuck at stopping the animation. I am set the delay like 20 second long. Form submit trigger the animation but how can i stop the animation on success. Here is my code:

    $scope.submitFunc = function() {
    $scope.submitPromise = fakeFac.success();
    $http({
    method  : 'POST',
    url    
    data   
    headers 
       })
    .success(function(formData) {
			  $scope.submitPromise = false;
    })
    }

**Comment by johannesjo** [comment]
You need to actually return a promise:
```
    $scope.submitFunc = function() {
    $scope.submitPromise = fakeFac.success();
    return $http({
    method  : 'POST',
    url    
    data   
    headers 
       })
    .success(function(formData) {
			  $scope.submitPromise = false;
    })
    }
```
