### ISSUE TITLE
Spinner outside of button when using with angularjs 1.6.3

### ISSUE THREAD

**Issue by saeidalidadi** [johannesjo/angular-promise-buttons#40]
I am using this module with angular 1.6.3 and inside my form but the spinner have been located outside of the submit button and spins forever.

**Comment by johannesjo** [comment]
Thanks for reporting. I'll try to check what's going on this Friday.

**Comment by johannesjo** [comment]
I can't really reproduce what you're dealing with. Could you provide a plunkr maybe?

**Comment by saeidalidadi** [comment]
Ok, I will create one asap.
