### ISSUE TITLE
Conflict between ng-disabled and promise button

### ISSUE THREAD

**Issue by landrytaffin** [johannesjo/angular-promise-buttons#45]
Hello,

During the promise resolution, if ng-disabled value changes to false, then once the promise is resolved, the disabled attribute is always removed (not taking into account the state of ng-disabled).

We made a small fix on our local version:
1) We added ngDisabled in the directive's scope
2) We modified handleLoadingFinished to take into account ngDisabled value

So here it is:
```
function handleLoadingFinished(btnEl) {
    if ((!cfg.minDuration || minDurationTimeoutDone) && promiseDone) {
        if (cfg.btnLoadingClass) {
            btnEl.removeClass(cfg.btnLoadingClass);
        }
        if (cfg.disableBtn && !scope.ngDisabled) {
            btnEl.removeAttr('disabled');
        }
    }
}
```
AND
```
return {
    restrict: 'EA',
    priority: angularPromiseButtons.config.priority,
    scope: {
        promiseBtn: '=',
        promiseBtnOptions: '=?',
        ngDisabled: '='
    },
    ...
```

Could you include this as a feature in you next version of the directive ?
Thank you.

**Comment by johannesjo** [comment]
Hey! Thanks for the suggestion. I implemented your fix.
