### ISSUE TITLE
Seperate configuration

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/angular-promise-buttons#5]
One should able to configure separately for individual button

**Comment by johannesjo** [comment]
Should be easy to do. I look into this.

**Comment by johannesjo** [comment]
Should be resolved by https://github.com/johannesjo/angular-promise-buttons/commit/d7e0c876e07f85c2ea7799c2e2dca9c55481fb7a

**Comment by tushariscoolster** [comment]
@johannesjo  Thanks
