### ISSUE TITLE
Publish angular-promise-buttons to npm

### ISSUE THREAD

**Issue by Den-dp** [johannesjo/angular-promise-buttons#6]
I found that you have `package.json` but it looks like your package wasn't published to npm.

As an npm user I want to install angular-promise-buttons package with

```
npm install angular-promise-buttons --save
```

Here you can get more information about the publishing process:
https://docs.npmjs.com/getting-started/publishing-npm-packages

Also this screencasts might be useful https://egghead.io/series/how-to-write-an-open-source-javascript-library (check videos about npm)

**Comment by johannesjo** [comment]
Here you go:
https://www.npmjs.com/package/angular-promise-buttons

**Comment by Den-dp** [comment]
Thanks!
