### ISSUE TITLE
Allow ng-click function to return promise

### ISSUE THREAD

**Issue by SoftwareWarlock** [johannesjo/angular-promise-buttons#7]
It'd be nice to be able to return the promise in the function call in ng-click, and not have to muck up the scope with promises that only get used once and overwritten next time the button is pressed.

[kirstein/angular-autodisable](https://github.com/kirstein/angular-autodisable) does it this way, and I feel like it's a nice way to keep the code functional and clean. 

Being able to use a scope variable promise is nice, and allows this library to be more flexible, but I think adding this would help to make it even more robust. Thoughts?

**Comment by johannesjo** [comment]
Hello! Thanks for the suggestion. I tried this before, but I was somehow not satisfied by the way you would have to handle to handle form-submits. I might give it another shot. I'm not yet quite sure, how to handle backwards compatibility.

**Comment by SoftwareWarlock** [comment]
I can see where that would be a problem. I was planning on looking at the source code more, as well as the source of angular-autodisable to see how they do it. I'll let you know if I have any suggestions or ideas.

**Comment by johannesjo** [comment]
Thank you! We're you able to make any progress on this one. If not might give it a shot for myself.

**Comment by SoftwareWarlock** [comment]
Sorry, just got back from vacation, haven't got a chance to look at it yet, but I can do it today.

**Comment by SoftwareWarlock** [comment]
So it seems like the other lib manages this functionality by taking care of calling `ngClick` and `ngSubmit` itself. They also have to put the directive on the form instead of the button. I think it'd be possible to do without introducing any breaking changes, but the solution probably won't be very simple.

**Comment by johannesjo** [comment]
No hurry. Vacation comes first! :)

Do you wanna give it a shot or should I?

**Comment by SoftwareWarlock** [comment]
You can go ahead. It's taken me longer to ramp up on the source code than I expected.

**Comment by johannesjo** [comment]
Oki great. I'm on it. Maybe you could have  a look at the pull-request once its done?

**Comment by johannesjo** [comment]
here is the PR https://github.com/johannesjo/angular-promise-buttons/pull/9/files
